version: "3.9"

services:

  user-service:
    build:
      context: ./user-service
    env_file:
      - ./user-service/.env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./user-service/.env:/app/.env
    networks:
      - backend
      
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  public-api-service:
    build:
      context: ./public-api
    env_file:
      - ./public-api/.env
    ports:
      - "9000:9000"
    volumes:
      - ./public-api/.env:/app/.env
    networks:
      - backend

  listing-service:
    build:
      context: ./listing-service
    env_file:
      - ./listing-service/.env
    volumes:
      - ./listing-service/data:/app/data
      - ./listing-service/.env:/app/.env
    ports:
      - "6000:6000"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
